server:
  port: 9191
spring:
  cloud:
    gateway:
      routes:
      - id: flightuser-ws
        uri: http://localhost:9095
        predicates:
        - Path=/api/v1.0/user/flight/**
      - id: flightadmin-ws
        uri: http://localhost:9094
        predicates:
        - Path=/api/v1.0/admin/flight/**
  application:
    name: api-gateway
           
          

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
